customer/urls.py
from django.urls import path
from.import views
app_name='customer'


urlpatterns=[
    path('',views.cuhome ,name="ncuhome"),
    
    path('sign',views.signin , name="nsign"),
    path('user', views.userpage,name="userpg"),
    path('userin', views.userinpage,name="userinpg"),
    path('rest', views.vrest,name="nrest"),
    path('deliciaRest', views.vdeliciaRest,name="ndeliciaRest"),
    path('verifyotp',views.otpverification,name="otpverify"),
    path('login',views.login,name='login'),
    path('customerdetail',views.customerdetails,name='customerdetails_n'),
    
    path('customerupdate',views.cust_update_v,name='customerupdate'),
    path('deletecustomer/<int:customerid>',views.delete_customer_v, name="cust_delete_n"),
    path('custupdate/<int:customerid>',views.cust_update_v, name="cust_update_n"),
    path('checkemailexist',views.checkemailuser,name='checkemail'),
    path('otp',views.cust_otp_v,name="cust_otp_n"),
    path('hotel',views.hotels,name='hotel'),
    path('plslogin',views.plslogin,name='loginpls'),
    path('photographer',views.photographer,name='photographer'),
    path('driver',views.driver,name='driver'),
    path('guide',views.guide,name='guide'),
    path('register1',views.register1,name='register1')
    
]

guidemeproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('customer.urls')),
    path('member',include('member.urls')),
    path('gmadmin/',include('gmadmin.urls'))
   
]

member/urls.py
from django.urls import path
from.import views
app_name='member'


urlpatterns=[
    path('',views.mehome, name="nmehome"),
    path('guidereg', views.guidereg, name="nguidereg" ),
    path('hotelsreg',views.hotelreg, name="nhotelreg"),
    path('restaurentreg',views.restaurentreg, name="nrestaurentreg"),
    path('photographerreg',views.photographerreg, name="nphotographerreg"),
    path('driverreg',views.driverreg, name="ndriverreg"),
    
    path('memlogin/',views.login_mem,name='memlogin'),
    path('logindri/',views.login_driver , name="logindri"),
    path('logingui',views.login_guide , name="logingui"),
    path('loginhot',views.login_hotel , name="loginhot"),
    path('phlogin/',views.phlogin, name="nphlogin"),

    path('restm/',views.rest_mem_details,name='nrestmem'),
    path('phm/',views.ph_mem_details,name='nphmem'),
    path('homem/',views.ho_mem_details,name="nhomem"),
    
    path('deleterestmem/<int:restid>',views.delete_rest_mem,name='rest_mem_delete'),
    path('deletephmem/<int:phid>',views.delete_ph_mem,name='ph_mem_delete'),
    path('deletehomem/<int:hoid>',views.delete_ho_mem,name='ho_mem_delete'),
    
    path('acceptrestmem/<int:restid>',views.accept_rest_mem,name='rest_mem_accept'),
    path('homemaccept/<int:hoid>',views.ho_mem_accept,name="ho_mem_accept"),
    path('phmemaccept/<int:phid>',views.ph_mem_accept,name="ph_mem_accept"),
    path('drmemaccept/<int:drid>',views.dr_mem_accept,name="dr_mem_accept"),

    path('rejecting/<int:rrid>',views.rest_mem_reject,name="rest_mem_reject"),
    path('phmemreject/<int:phid>',views.ph_mem_reject,name="ph_mem_reject"),
    path('homemreject/<int:hoid>',views.ho_mem_reject,name="ho_mem_reject"),
    path('drmemreject/<int:drid>',views.dr_mem_reject,name="dr_mem_reject"),

    path('resdashboard/',views.res_dashboard, name ="resdashboard"),
    path('phdashboard/',views.ph_dashboard,name="phdashboard"),
    
    
    path('accept',views.accept,name="accepted"),
    path('reject',views.reject,name="rejected"),
    path('waiting/',views.waiting,name="waiting"),
    
    path('waitinglist/',views.waiting_list,name="waitinglist")

]

customer/models.py
from django.db import models


# Create your models here.
class Contactmessage (models.Model) :
    contact_email = models.TextField(max_length = 100,db_column='email')
    contact_message = models.TextField(max_length = 1000,db_column='message')
    class Meta :
        db_table='contactmessage'
        
class Registrationcustomer(models.Model) :
    fname = models.TextField(max_length=50,db_column='firstname',null=True)
    lname = models.TextField(max_length=50,db_column='lastname',null=True)
    email = models.TextField(max_length=100,db_column='mail',null=True)
    mob = models.TextField(max_length=10,db_column='mobile',null=True)
    city = models.TextField(max_length=50,db_column='city',null=True)
    state = models.TextField(max_length=50,db_column='state',null=True)
    crtepswd = models.TextField(max_length=100,db_column='createdpassword',null=True)
    pswd = models.TextField(max_length=100,db_column='password',null=True)
    otp = models.TextField(max_length=6,db_column='otp',null=True)
    status = models.TextField(max_length=10,db_column='status',null=True)
    class Meta :
        db_table='customer_registration_details'
        

customer/views.py
from django.shortcuts import render,redirect
from . models import *
from random import randint
from django.core.mail import send_mail
from django.conf import settings
from django.http import JsonResponse

# Create your views here.
def cuhome (request):
    
    if request.method == "POST" :
        mail = request.POST['c_email']
        message = request.POST['c_message']
        contactform = Contactmessage (contact_email = mail , contact_message = message)
        contactform.save()
        return render (request, "customer/cuhome.html" , {'msg' : 'we will get back to you as soon as possible'})
    return render (request,'customer/cuhome.html')


  
def register1 (request):
    return render (request,'customer/register1.html')   

def signin (request):
    if request.method == "POST" :
        fname = request.POST['fname']
        lname = request.POST['lname']
        email = request.POST['email']
        mob = request.POST['mob']
        city = request.POST['city']
        state = request.POST['state']
        crtpswd = request.POST['pswd1']
        pswd = request.POST['pswd2']
        customer_exist = Registrationcustomer.objects.filter(email=email).exists()
        if not customer_exist :
            otp = randint(1000,9999)
            send_mail(
                'please verify your otp',
                str(otp),
                settings.EMAIL_HOST_USER,
                [email]
            )
        regc = Registrationcustomer(fname=fname, lname=lname, email=email, city=city, mob=mob, state=state, otp=otp, crtepswd=crtpswd, pswd=pswd)
        
        regc.save()
        customer = Registrationcustomer.objects.get(email=email)
        request.session['customerid']=customer.id
        return redirect('customer:cust_otp_n')
        return render (request,'customer/login.html')
    return render (request,'customer/sign.html')    

def userpage (request):
    return render (request,'customer/user.html')    

def userinpage (request):
    return render (request,'customer/userin.html')    


def vrest (request):
    return render (request,'customer/restaurent.html')    

def vdeliciaRest (request):
    return render (request,'customer/deliciaRest.html')
def otpverification(request):
    return render(request,'customer/verifyotp.html')
def login(request):
    if request.method =='POST':
        email = request.POST['email']
        password = request.POST['password']
        customer_exist = Registrationcustomer.objects.filter(email=email,pswd=password).exists()
        if customer_exist :
            customer = Registrationcustomer.objects.get(email=email,pswd=password)
            request.session['customerid']=customer.id
            if customer.status == 'toverify':
                otp = randint(1000,9999)
                send_mail(
                'please verify your otp',
                str(otp),
                settings.EMAIL_HOST_USER,
                [customer.customer_mail]
                )
                customer.otp=otp
                customer.save()
                return redirect('customer:cust_otp_n')
            else :
                return redirect('customer:userinpg')
        else :
                return render(request, 'customer/login.html', {'msg':'invalid username/password'})
    
    return render(request,'customer/login.html')
def cust_otp_v(request):
    if request.method == 'POST' :
        otp = request.POST['otp']
        c_id = request.session['customerid']
        customer =Registrationcustomer.objects.get(id=c_id)
        if otp==customer.otp :
            Registrationcustomer.objects.filter(id=c_id).update(status='verified')
            return redirect('customer:userinpg')
        else :
            return render (request,'customer/otp.html' ,{'msg':'invalid otp'})
    return render(request, 'customer/otp.html')
def customerdetails(request):
    customers = Registrationcustomer.objects.all()
    return render(request,'customer/customerdetails.html',{'cust':customers})


def cust_update_v(request,customerid):
    # if request.method =='POST':
    #     fname = request.POST['fname']
    #     lname = request.POST['lname']
    #     email = request.POST['email']
    #     mob = request.POST['mob']
    #     city = request.POST['city']
    #     state = request.POST['state']
    #     crtpswd = request.POST['pswd1']
    #     pswd = request.POST['pswd2']
        
    #     Registrationcustomer.objects.filter(id=customerid).update(fname=fname ,lname=lname, email=email, mob=mob, city=city,state=state,crtepswd=crtpswd,pswd=pswd)
    #     return redirect('customer:login')
    # updatecust = Registrationcustomer.objects.get(id=customerid)
    return render (request,'customer/mpcustomer.html') 
    
def delete_customer_v(request,customerid):
    Registrationcustomer.objects.get(id=customerid).delete()
    return redirect('customer:customerdetail_n')    
def checkemailuser(request):
    mailid = request.POST['email']
    user = Registrationcustomer.objects.filter(email=mailid).exists()
    if user :
        return JsonResponse({
            'is_available' : False
        })
    else :
        return JsonResponse({
            'is_available' : True
        })
           
def hotels(request):
    return render(request,'customer/hotel.html')
def plslogin(request):
    return render(request,'customer/loginpls.html')
def photographer(request):
    return render(request,'customer/photographer.html')
def driver(request):
    return render(request,'customer/driver.html')
def guide(request):
    return render(request,'customer/guide.html')




    

customer/templates/customer/customerdetails.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>guideME</title>

    <link  rel="stylesheet" href="{% static 'css/stylelogin.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">    
 
 
</head>
<body>
  <div class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-light bg-light py-3 py-lg-5">
      <a class="navbar-brand" href="#">
        <img src="{% static 'images/logo.png' %}" width="50" height="50" class="d-inline-block align-top" alt="">
        
      </a>
      <a class="navbar-brand headding" href="#">
        <b>guideME</b>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <!-- <div class="navbar-nav ml-auto">
          
            <li><a class="nav-link active" href="#">Home <span class="sr-only">(current)</span></a></li>
            <li><a class="nav-link" href="#">About us</a></li>
            <li><a class="nav-link" href="#">Contact</a></li>
            <li class="nav-item dropdown" style="float: right"!importent>
              <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
              Services provides
              </a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="#">restaurents</a>
                  <a class="dropdown-item" href="#">hotels</a>
                  <a class="dropdown-item" href="#">public transportation details</a>
                  <a class="dropdown-item" href="#">people profiles</a>
                  <a class="dropdown-item" href="#">guides</a>
                  <a class="dropdown-item" href="#">photographers</a>
                  <a class="dropdown-item" href="#">toilets</a>
                </div>
            </li>
        
        
        </div> -->
      </div>
    </nav>





 <table border="1">
    <tr>
        <th>first name</th>
        <th>last name</th>
        <th>mail</th>
        <th>mobile</th>
        <th>city</th>
        <th>state</th>
        <th>delete</th>
        <th>update</th>
    </tr>
    {% for customer in cust %}
        <tr>
            <td>{{customer.fname}}</td>
            <td>{{customer.lname}}</td>
            <td>{{customer.email}}</td>
            <td>{{customer.mob}}</td>
            <td>{{customer.city}}</td>
            <td>{{customer.state}}</td>
            <td><a href="{% url 'customer:cust_update_n' customer.id %}">delete</a></td>
          
        </tr>
    {% endfor %}
</table> 

    
</body>
</html>

customer/templates/customer/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>guideME</title>

    <link  rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">    
<style>
  .homebutn{
    border: none;
    width: 150px;
    font-size: 25px;
    padding: 1px;
    color: rgb(13, 56, 56);
    background-color: transparent;
    cursor: pointer;
    transition: 0.5s;
    border-radius: 100px;
    
        

    }
    .homebutn:hover {
        border:1px solid rgb(99, 177, 222);
        
    }
</style> 
 
</head>
<body>
  <div class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-light bg-light py-3 py-lg-5">
      <a class="navbar-brand" href="#">
        <img src="{% static 'images/logo.png' %}" width="50" height="50" class="d-inline-block align-top" alt="">
        
      </a>
      <a class="navbar-brand headding" href="#">
        <b style="font-size: 50px;">guideME</b>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
          

            <li><a class="nav-link active" href="{% url 'customer:ncuhome' %}"><button class="homebutn">home</button></a></li>
          </div>
      </div>
    </nav>
</body>
</html>    

customer/templates/customer/register1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>guideME</title>

    <link  rel="stylesheet" href="{% static 'css/styleregister1.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">    
</head> 
<style>
  .homebutn{
    border: none;
    width: 150px;
    font-size: 25px;
    padding: 1px;
    color: rgb(13, 56, 56);
    background-color: transparent;
    cursor: pointer;
    transition: 0.5s;
    border-radius: 100px;
    
        

    }
    .homebutn:hover {
        border:1px solid rgb(99, 177, 222);
        
    }
    body {
    display: flex;
    align-items: center;
    justify-content: center;
    flex-wrap: wrap;
    background-color: rgb(213, 226, 222);
}
.container {
    background-color: rgb(124, 165, 165);
    display: inline-block;
    font-size: 160px;
    margin-top: 100px;
    margin-left: 270px;
    max-width: 315px;
    min-width: 230px;
    overflow: hidden;
    position: relative;
    text-align: center;
    width: 100%;
}
.container * {
  -webkit-box-transition:all 0.35s ease;
  transition: all 0.35s ease;

}
.container h3 {
  background-color: rgb(176, 195, 196);
  border: 1px solid antiquewhite;
  letter-spacing:1px ;
  margin:0 ;
  padding:5px 10px ;
  color: rgb(12, 53, 66);
  font-size: 80px;

}
.container::before,
.container::after{
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  -webkit-box-transition:all 0.35s ease;
  transition: all 0.35s ease;
  background-color:rgb(176, 195, 196) ;
  border-left:3px solid black ;
  border-right: 3px solid black;
  content: '';
  opacity: 0.9;
  z-index: 1;

}
.container::before{
  -webkit-transform: skew(45deg) translateX(-155%);
  transform: skew(45deg) translateX(-155%);

}
.container::after{
  -webkit-transform: skew(45deg) translateX(155%);
  transform: skew(45deg) translateX(155%);

}
.container img {
  backface-visibility: hidden;
  max-width: 100%;
  
}
.container figcaption{
  top: 50%;
  left: 50%;
  position: absolute;
  z-index: 2;
  -webkit-transform:translate(-50%,-50%) scale(0.5);
  transform: translate(-50%,-50%) scale(0.5);
  opacity: 0;
}
.container a {
  position:absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  z-index: 3;

}
.container:hover img {
  opacity:0.5 ;
}  
.container:hover figcaption,
.container:hover figcaption {
  -webkit-transform: translate(-50% -50%) scale(1);
  transform: translate(-50% -50%) scale(1);
  opacity: 1;
}



</style>   
    
    <body>
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-light bg-light py-3 py-lg-5">
          <a class="navbar-brand" href="#">
            <img src="{% static 'images/logo.png' %}" width="50" height="50" class="d-inline-block align-top" alt="">
            
          </a>
          <a class="navbar-brand headding" href="#">
            <b style="font-size: 50px;">guideME</b>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ml-auto">
              
    
                <li><a class="nav-link active" href="{% url 'customer:ncuhome' %}"><button class="homebutn">home</button></a></li>
              </div>
          </div>
        </nav>
        
        <figure class="container">
          <img src="{% static 'images/business.png' %}" alt="" srcset="">
          <figcaption><h3>user</h3></figcaption>
          <a href="{% url 'customer:nsign' %}"></a>
        </figure>
        <figure class="container">
          <img src="{% static 'images/user.png' %}" alt="" srcset="">
          <figcaption><h3>member</h3></figcaption>
          
          <a href="{% url 'member:nmehome' %}"></a>
        </figure>
      </div>



<script src="{% static 'javascript/gallery.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>    
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script> 
          
</body>
</html>                

customer/templates/customer/userin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>guideME</title>

    <link  rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">    
    <style>
      .loginbutn{
          width: 100px;
          border: 0px solid;
          position: relative;
          padding: 15px 0;
          text-align: center;
          margin: 20px 10px;
          font-weight: 50px;
          font-size: 20px;
          background:transparent;
          color: #074c5d;
          cursor: pointer;
          transition: all 0.2s ease;
          border-radius: 100px;
          transition: 1.5s;
          
  
      }
      .loginbutn:hover {
          box-shadow: 0 5px 8px 0 #3c93b3 inset,0 5px 8px 0 #3c93b3 ,
                      0 5px 8px 0 #3c93b3 inset,0 5px 8px 0 #3c93b3 ;
          
      }
      body {
    width: 100%;
    display: flex;
    align-items: center;
    justify-content: center;
    flex-wrap: wrap;
    background-color: rgb(213, 226, 222);
}
.container {
    background-color: rgb(124, 165, 165);
    display: inline-block;
    font-size: 160px;
    margin: 10px;
    margin-top: 100px;
    margin-left: 120px;
    max-width: 315px;
    min-width: 230px;
    overflow: hidden;
    position: relative;
    text-align: center;
    width: 100%;
}
.container * {
  -webkit-box-sizing: border-box;
  box-sizing: border-box;
  -webkit-box-transition:all 0.35s ease;
  transition: all 0.35s ease;

}
.container h3 {
  background-color: rgb(176, 195, 196);
  border: 1px solid antiquewhite;
  letter-spacing:1px ;
  margin:0 ;
  padding:5px 10px ;
  color: rgb(12, 53, 66);
  font-size: 80px;

}
.container::before,
.container::after{
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  -webkit-box-transition:all 0.35s ease;
  transition: all 0.35s ease;
  background-color:rgb(176, 195, 196) ;
  border-left:3px solid black ;
  border-right: 3px solid black;
  content: '';
  opacity: 0.9;
  z-index: 1;

}
.container::before{
  -webkit-transform: skew(45deg) translateX(-155%);
  transform: skew(45deg) translateX(-155%);

}
.container::after{
  -webkit-transform: skew(45deg) translateX(155%);
  transform: skew(45deg) translateX(155%);

}
.container img {
  backface-visibility: hidden;
  max-width: 100%;
  
  
}
.container figcaption{
  top: 50%;
  left: 50%;
  position: absolute;
  z-index: 2;
  -webkit-transform:translate(-50%,-50%) scale(0.5);
  transform: translate(-50%,-50%) scale(0.5);
  opacity: 0;
  -webkit-box-shadow: 0  0 10px rgb(70, 182, 199);
  box-shadow: 0  0 10px rgb(67, 161, 180) ;
}
.container a {
  position:absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  z-index: 3;

}
.container:hover img {
  opacity:0.5 ;
}  
.container:hover::before ,
.container:hover::before {
  transform:skew(45deg) translateX(-55%) ;
  -webkit-transform:skew(45deg) translateX(-55%);
}
.container:hover::after,
.container:hover::after {
  transform:skew(45deg) translateX(55%) ;
  -webkit-transform:skew(45deg) translateX(55%);
}
.container:hover figcaption,
.container:hover figcaption {
  -webkit-transform: translate(-50% -50%) scale(1);
  transform: translate(-50% -50%) scale(1);
  opacity: 1;
}
     
    
   </style>
 
</head>
<body>
  <div class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-light bg-light py-3 py-lg-5">
      <a class="navbar-brand" href="#">
        <img src="{% static 'images/logo.png' %}" width="50" height="50" class="d-inline-block align-top" alt="">
        
      </a>
      <a class="navbar-brand headding" href="#">
        <b style="font-size: 50px;">guideME</b>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
          

            <li><a class="nav-link active" href="{% url 'customer:login' %}"><button class="loginbutn">home</button></a></li>
            <li><a class="nav-link active" href="{% url 'customer:register1' %}"><button class="loginbutn">logout</button></a></li>
            
            
            
            
              
        </div>
      </div>
    </nav>
    <div class="row">
      <figure class="container col-lg-4 col-4">
        <img src="{% static 'images/friend.png' %}" alt="" srcset="">
        <figcaption><h3>make friends here</h3></figcaption>
        <a href="{% url 'customer:nsign' %}"></a>
      </figure>
      <figure class="container col-lg-4 col-4">
        <img src="{% static 'images/restau.png' %}" alt="" srcset="">
        <figcaption><h3>restaurent</h3></figcaption>
        <a href=""></a>
      </figure>
      <figure class="container col-lg-4 col-4">
        <img src="{% static 'images/hotl.png' %}" alt="" srcset="">
        <figcaption><h3>hotel</h3></figcaption>
        <a href="{% url 'customer:nsign' %}"></a>
      </figure>
    </div>
    <div class="row">

      
      <figure class="container col-lg-4 col-4">
        <img src="{% static 'images/guides.png' %}" alt="" srcset="">
        <figcaption><h3>guide</h3></figcaption>
        <a href=""></a>
      </figure>
      <figure class="container col-lg-4 col-4">
        <img src="{% static 'images/cab.png' %}" alt="" srcset="">
        <figcaption><h3>cab driver</h3></figcaption>
        <a href="{% url 'customer:nsign' %}"></a>
      </figure>
      <figure class="container col-lg-4 col-4">
        <img src="{% static 'images/photo.png' %}" alt="" srcset="">
        <figcaption><h3>photographer</h3></figcaption>
        <a href=""></a>
      </figure>
    </div> 
      
      
    
  </div>

  
</body>
</html>
    