gmadmin/urls.py
from django.urls import path
from.import views
app_name='gmadmin'


urlpatterns=[
    path('login',views.adhome , name='login'),
    path('applications/', views.application , name='application')
    
]

guidemeproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('customer.urls')),
    path('member',include('member.urls')),
    path('gmadmin/',include('gmadmin.urls'))
   
]

member/urls.py
from django.urls import path
from.import views
app_name='member'


urlpatterns=[
    path('',views.mehome, name="nmehome"),
    path('guidereg', views.guidereg, name="nguidereg" ),
    path('hotelsreg',views.hotelreg, name="nhotelreg"),
    path('restaurentreg',views.restaurentreg, name="nrestaurentreg"),
    path('photographerreg',views.photographerreg, name="nphotographerreg"),
    path('driverreg',views.driverreg, name="ndriverreg"),
    
    path('memlogin/',views.login_mem,name='memlogin'),
    path('logindri/',views.login_driver , name="logindri"),
    path('logingui',views.login_guide , name="logingui"),
    path('loginhot',views.login_hotel , name="loginhot"),
    path('phlogin/',views.phlogin, name="nphlogin"),

    path('restm/',views.rest_mem_details,name='nrestmem'),
    path('phm/',views.ph_mem_details,name='nphmem'),
    path('homem/',views.ho_mem_details,name="nhomem"),
    
    path('deleterestmem/<int:restid>',views.delete_rest_mem,name='rest_mem_delete'),
    path('deletephmem/<int:phid>',views.delete_ph_mem,name='ph_mem_delete'),
    path('deletehomem/<int:hoid>',views.delete_ho_mem,name='ho_mem_delete'),
    
    path('acceptrestmem/<int:restid>',views.accept_rest_mem,name='rest_mem_accept'),
    path('homemaccept/<int:hoid>',views.ho_mem_accept,name="ho_mem_accept"),
    path('phmemaccept/<int:phid>',views.ph_mem_accept,name="ph_mem_accept"),
    path('drmemaccept/<int:drid>',views.dr_mem_accept,name="dr_mem_accept"),

    path('rejecting/<int:rrid>',views.rest_mem_reject,name="rest_mem_reject"),
    path('phmemreject/<int:phid>',views.ph_mem_reject,name="ph_mem_reject"),
    path('homemreject/<int:hoid>',views.ho_mem_reject,name="ho_mem_reject"),
    path('drmemreject/<int:drid>',views.dr_mem_reject,name="dr_mem_reject"),

    path('resdashboard/',views.res_dashboard, name ="resdashboard"),
    path('phdashboard/',views.ph_dashboard,name="phdashboard"),
    
    
    path('accept',views.accept,name="accepted"),
    path('reject',views.reject,name="rejected"),
    path('waiting/',views.waiting,name="waiting"),
    
    path('waitinglist/',views.waiting_list,name="waitinglist")

]

gmadmin/models.py
from django.db import models

# Create your models here.

gmadmin/views.py
from django.shortcuts import render
from . models import *
# Create your views here.
def adhome (request):
    return render (request,'gmadmin/adhome.html')

def application (request):
    return render (request, 'gmadmin/applications.html')

gmadmin/templates/gmadmin/adhome.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>guideME</title>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link  rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">    
<style>
  
  .homebutn{
    border: none;
    width: 150px;
    font-size: 25px;
    padding: 1px;
    color: rgb(13, 56, 56);
    background-color: transparent;
    cursor: pointer;
    transition: 0.5s;
    border-radius: 100px;
    
        

    }
    .homebutn:hover {
        border:1px solid rgb(21, 94, 46);
        
    }
    .wrapper{
        display:flex;
        justify-content: center;
        align-items: center;
        min-height: 72vh;
        background: url('images/restauremt.jpg');
        background-size:cover;
        background-position:center;

    }
    .wrap{
        width: 420px;
        background-color: rgb(17, 33, 26);
        border: 2px solid rgba(255,255,255,.2);
        backdrop-filter: blur(20px);
        box-shadow: 0 0 10px rbga(0,0,0,.2);
        color: #fff;
        border-radius: 10px;
        padding: 30px 40px;
    }
    .wrapper .wrap h1 {
        font-size: 36px;
        text-align: center;

    }
    .wrapper .wrap .input-box {
        position: relative;
        width: 100%;
        height: 50px;
        margin:30px 0
    }
    .wrap .input-box input {
        width: 100%;
        height: 100%;
        background: transparent;
        border: none;
        outline: none;
        border: 2px solid rgba(255, 255, 255, .2) ;
        border-radius: 40px;
        font-size: 16px;
        color: #fff;
        padding: 20px 45px 20px 20px;
    }
    .input-box input::placeholder {
        color: #fff;
    }
   .input-box i {
    position: absolute;
    right: 20px;
    top: 50%;
    transform: translateY(-50%);
    font-size: 20px;
   } 
   .wrap .remember-forgot {
    display: flex;
    justify-content: space-between;
    font-size: 14.5px;
    margin:-15px 0 15px;

   }
   .remember-forgot label input {
        accent-color: #fff;
        margin-right: 3px;
   }
   .remember-forgot a {
    color: #fff;
    text-decoration: none;

   }
   .remember-forgot a:hover {
    text-decoration: underline;
   }
   .wrap .btn {
    width: 100%;
    height: 45px;
    background: #fff;
    border: none;
    outline: none;
    border-radius: 40px;
    box-shadow: 0 0 10px rgba(0, 0, 0, .1);
    cursor: pointer;
    font-size: 16px;
    color: #333;
    font-weight: 600;
   }
   .wrap .register-link{
    font-size: 14.5px;
    text-align: center;
    margin: 20px 0 15px;
   }
   .register-link p a {
    color: #fff;
    text-decoration: none;
    font-weight: 600;
   }
   ..register-link p a:hover{
    text-decoration: underline;
   }

    

</style> 
 
</head>
<body>
  <div class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-light bg-light py-3 py-lg-5">
      <a class="navbar-brand" href="#">
        <img src="{% static 'images/logo.png' %}" width="50" height="50" class="d-inline-block align-top" alt="">
        
      </a>
      <a class="navbar-brand headding" href="#">
        <b style="font-size: 50px;">guideME</b>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
          

          </div>
      </div>
    </nav>
    <div class="wrapper">
        <div class="wrap">
            <form action="" method="post">
                {% csrf_token %}
                <h1>Login</h1>
                <div class="input-box">
                    <input type="text" name="" id="" placeholder="Username" required>
                    <i class='bx bxs-user'></i>
                </div>
                <div class="input-box">
                    <input type="text" name="" id="" placeholder="Password" required>
                    <i class='bx bxs-lock-alt'></i>
                </div>
                <div class="remember-forgot">
                    <label for=""><input type="checkbox" name="" id="">Remember Me</label>
                    <a href="#">Forgot Password</a>
                </div>
                <button type="submit" class="btn" >Login</button>
                   
            </form>
        </div>
    </div>

</body>
</html>      

gmadmin/templates/gmadmin/applications.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>guideME</title>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link  rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">    
<style>
  
  .homebutn{
    border: none;
    width: 150px;
    font-size: 25px;
    padding: 1px;
    color: rgb(13, 56, 56);
    background-color: transparent;
    cursor: pointer;
    transition: 0.5s;
    border-radius: 100px;
    
        

    }
    .homebutn:hover {
        border:1px solid rgb(21, 94, 46);
        
    }
    container {
    background-color: rgb(52, 117, 81);
    display: inline-block;
    font-size: 160px;
    margin: 10px;
    margin-top: 100px;
    margin-left: 120px;
    max-width: 315px;
    min-width: 230px;
    overflow: hidden;
    position: relative;
    text-align: center;
    width: 100%;
}
.container * {
  -webkit-box-sizing: border-box;
  box-sizing: border-box;
  -webkit-box-transition:all 0.35s ease;
  transition: all 0.35s ease;

}
.container h3 {
  background-color: rgb(201, 228, 218);
  border: 1px solid rgb(23, 82, 55);
  letter-spacing:1px ;
  margin:0 ;
  padding:5px 10px ;
  color: rgb(3, 53, 12);
  font-size: 80px;

}
.container::before,
.container::after{
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  -webkit-box-transition:all 0.35s ease;
  transition: all 0.35s ease;
  background-color:rgb(65, 166, 119) ;
  border-left:3px solid black ;
  border-right: 3px solid black;
  content: '';
  opacity: 0.9;
  z-index: 1;

}
.container::before{
  -webkit-transform: skew(45deg) translateX(-155%);
  transform: skew(45deg) translateX(-155%);

}
.container::after{
  -webkit-transform: skew(45deg) translateX(155%);
  transform: skew(45deg) translateX(155%);

}
.container img {
  backface-visibility: hidden;
  max-width: 100%;
  
  
}
.container figcaption{
  top: 50%;
  left: 50%;
  position: absolute;
  z-index: 2;
  -webkit-transform:translate(-50%,-50%) scale(0.5);
  transform: translate(-50%,-50%) scale(0.5);
  opacity: 0;
  -webkit-box-shadow: 0  0 10px rgb(17, 137, 95);
  box-shadow: 0  0 10px rgb(17, 137, 95) ;
}
.container a {
  position:absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  z-index: 3;

}
.container:hover img {
  opacity:0.5 ;
}  
.container:hover::before ,
.container:hover::before {
  transform:skew(45deg) translateX(-55%) ;
  -webkit-transform:skew(45deg) translateX(-55%);
}
.container:hover::after,
.container:hover::after {
  transform:skew(45deg) translateX(55%) ;
  -webkit-transform:skew(45deg) translateX(55%);
}
.container:hover figcaption,
.container:hover figcaption {
  -webkit-transform: translate(-50% -50%) scale(1);
  transform: translate(-50% -50%) scale(1);
  opacity: 1;
}
.row{
    margin-top: 30px;
    
}
body{
    background-color: rgb(49, 87, 71);
}
.card{
    margin-left: 2px;
}
.row{
    justify-content: center;
    align-items: center;
}


    
  
   
    

</style> 
 
</head>
<body>
  <div class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-light bg-light py-3 py-lg-5">
      <a class="navbar-brand" href="#">
        <img src="{% static 'images/logo.png' %}" width="50" height="50" class="d-inline-block align-top" alt="">
        
      </a>
      <a class="navbar-brand headding" href="#">
        <b style="font-size: 50px;">guideME</b>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
            <li><a class="nav-link active" href="{% url 'gmadmin:login' %}"><button class="homebutn">back</button></a></li>


          </div>
      </div>
    </nav>
    <div class="row">
      <div class="col-4">
        <div class="card" style="width: 18rem;">
          <img src="{% static 'images/restau.png' %}" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Waiting List</h5>
            <a href="{% url 'member:waitinglist' %}" class="btn btn-success">View</a>
          </div>
        </div>
      </div>
      <div class="col-4">
        <div class="card" style="width: 18rem;">
          <img src="{% static 'images/restau.png' %}" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Accepted</h5>
            <a href="{% url 'member:accepted' %}" class="btn btn-success">View</a>
          </div>
        </div>
      </div>
      <div class="col-4">
        <div class="card" style="width: 18rem;">
          <img src="{% static 'images/restau.png' %}" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Rejected</h5>
            <a href="{% url 'member:rejected' %}" class="btn btn-success">View</a>
          </div>
        </div>
      </div>
        
          
    </div>
     
    

        
        
      
    </div>
    

</body>
</html>      