customer/urls.py
from django.urls import path
from.import views
app_name='customer'


urlpatterns=[
    path('',views.cuhome ,name="ncuhome"),
    
    path('sign',views.signin , name="nsign"),
    path('user', views.userpage,name="userpg"),
    path('userin', views.userinpage,name="userinpg"),
    path('rest', views.vrest,name="nrest"),
    path('deliciaRest', views.vdeliciaRest,name="ndeliciaRest"),
    path('verifyotp',views.otpverification,name="otpverify"),
    path('login',views.login,name='login'),
    path('customerdetail',views.customerdetails,name='customerdetails_n'),
    
    path('customerupdate',views.cust_update_v,name='customerupdate'),
    path('deletecustomer/<int:customerid>',views.delete_customer_v, name="cust_delete_n"),
    path('custupdate/<int:customerid>',views.cust_update_v, name="cust_update_n"),
    path('checkemailexist',views.checkemailuser,name='checkemail'),
    path('otp',views.cust_otp_v,name="cust_otp_n"),
    path('hotel',views.hotels,name='hotel'),
    path('plslogin',views.plslogin,name='loginpls'),
    path('photographer',views.photographer,name='photographer'),
    path('driver',views.driver,name='driver'),
    path('guide',views.guide,name='guide'),
    path('register1',views.register1,name='register1')
    
]

gmadmin/urls.py
from django.urls import path
from.import views
app_name='gmadmin'


urlpatterns=[
    path('login',views.adhome , name='login'),
    path('applications/', views.application , name='application')
    
]

guidemeproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('customer.urls')),
    path('member',include('member.urls')),
    path('gmadmin/',include('gmadmin.urls'))
   
]

member/urls.py
from django.urls import path
from.import views
app_name='member'


urlpatterns=[
    path('',views.mehome, name="nmehome"),
    path('guidereg', views.guidereg, name="nguidereg" ),
    path('hotelsreg',views.hotelreg, name="nhotelreg"),
    path('restaurentreg',views.restaurentreg, name="nrestaurentreg"),
    path('photographerreg',views.photographerreg, name="nphotographerreg"),
    path('driverreg',views.driverreg, name="ndriverreg"),
    
    path('memlogin/',views.login_mem,name='memlogin'),
    path('logindri/',views.login_driver , name="logindri"),
    path('logingui',views.login_guide , name="logingui"),
    path('loginhot',views.login_hotel , name="loginhot"),
    path('phlogin/',views.phlogin, name="nphlogin"),

    path('restm/',views.rest_mem_details,name='nrestmem'),
    path('phm/',views.ph_mem_details,name='nphmem'),
    path('homem/',views.ho_mem_details,name="nhomem"),
    
    path('deleterestmem/<int:restid>',views.delete_rest_mem,name='rest_mem_delete'),
    path('deletephmem/<int:phid>',views.delete_ph_mem,name='ph_mem_delete'),
    path('deletehomem/<int:hoid>',views.delete_ho_mem,name='ho_mem_delete'),
    
    path('acceptrestmem/<int:restid>',views.accept_rest_mem,name='rest_mem_accept'),
    path('homemaccept/<int:hoid>',views.ho_mem_accept,name="ho_mem_accept"),
    path('phmemaccept/<int:phid>',views.ph_mem_accept,name="ph_mem_accept"),
    path('drmemaccept/<int:drid>',views.dr_mem_accept,name="dr_mem_accept"),

    path('rejecting/<int:rrid>',views.rest_mem_reject,name="rest_mem_reject"),
    path('phmemreject/<int:phid>',views.ph_mem_reject,name="ph_mem_reject"),
    path('homemreject/<int:hoid>',views.ho_mem_reject,name="ho_mem_reject"),
    path('drmemreject/<int:drid>',views.dr_mem_reject,name="dr_mem_reject"),

    path('resdashboard/',views.res_dashboard, name ="resdashboard"),
    path('phdashboard/',views.ph_dashboard,name="phdashboard"),
    
    
    path('accept',views.accept,name="accepted"),
    path('reject',views.reject,name="rejected"),
    path('waiting/',views.waiting,name="waiting"),
    
    path('waitinglist/',views.waiting_list,name="waitinglist")

]

member/views.py
from django.shortcuts import render,redirect
from . models import *
from random import randint
from django.core.mail import send_mail
from django.conf import settings
from django.http import JsonResponse

# Create your views here.
def mehome (request):
    return render (request,'member/mehome.html')
def guidereg (request):
    if request.method == 'POST':
        fullname = request.POST['fullname']
        dob = request.POST['dob']
        email = request.POST['email']
        mob = request.POST['mob']
        gender = request.POST['gender']
        propic = request.POST['propic']
        idtype = request.POST['idtype']
        idnum = request.POST['idnum']
        idimg = request.POST['idimg']
        sidtype = request.POST['sidtype']
        sidnum = request.POST['sidnum']
        sidimg = request.POST['sidming']
        natn = request.POST['natn']
        state = request.POST['state']
        dist = request.POST['dist']
        street = request.POST['street']
        post = request.POST['post']
        pin = request.POST['pin']
        place = request.POST['place']
        time = request.POST['time']
        wapp = request.POST['wapp']
        amount = request.POST['amount']
        user = request.POST['user']
        cuser = request.POST['cuser']
        pswd = request.POST['pswd']
        cpswd = request.POST['cpswd']
        guideregform = Guideregistration(full_name=fullname,date_of_birth=dob,e_mail=email,mobile_number=mob,gender=gender,profile_photo=propic,id_type=idtype,id_number=idnum,image_of_id=idimg,second_id_type=sidtype,second_id_number=sidnum,second_image_of_id=sidimg,nationality=natn,state=state,district=dist,street_name=street,post=post,pin_code=pin,wapp_number=wapp,available_place=place,available_time=time,amount_hours=amount,username=user,confirm_username=cuser,password=pswd,confirm_password=cpswd,status="waiting")
        guideregform.save()
    return render (request, 'member/guidereg.html')
def hotelreg (request):
    if request.method == 'POST':
        fullname = request.POST['fullname']
        dob = request.POST['dob']
        email = request.POST['email']
        mob = request.POST['mob']
        gender = request.POST['gender']
        propic = request.POST['propic']
        idtype = request.POST['idtype']
        idnum = request.POST['idnum']
        idimg = request.POST['idimg']
        sidtype = request.POST['sidtype']
        sidnum = request.POST['sidnum']
        sidimg = request.POST['sidimg']
        natn = request.POST['natn']
        state = request.POST['state']
        dist = request.POST['dist']
        street = request.POST['street']
        post = request.POST['post']
        pin = request.POST['pin']
        hotname = request.POST['hotname']
        hotad = request.POST['hotad']
        license = request.POST['license']
        photo = request.POST['photo']
        wapp = request.POST['wapp']
        time = request.POST['time']
        user = request.POST['user']
        cuser = request.POST['cuser']
        pswd = request.POST['pswd']
        cpswd = request.POST['cpswd']
        hotelregform = Hotelregistration(full_name=fullname,date_of_birth=dob,e_mail=email,mobile_number=mob,gender=gender,profile_photo=propic,id_type=idtype,id_number=idnum,image_of_id=idimg,second_id_type=sidtype,second_id_number=sidnum,second_image_of_id=sidimg,nationality=natn,state=state,district=dist,street_name=street,post=post,pin_code=pin,wapp_number=wapp,photos=photo,hotel_name=hotname,hotel_address=hotad,license_photo=license,working_hours=time ,username=user,confirm_username=cuser,password=pswd,confirm_password=cpswd,status='waiting')
        hotelregform.save()
        return redirect('member:loginhot')
    return render (request, 'member/hotelreg.html')
def restaurentreg (request):
    if request.method == 'POST':
        fullname = request.POST['fullname']
        dob = request.POST['dob']
        email = request.POST['email']
        mob = request.POST['mob']
        gender = request.POST['gender']
        propic = request.POST['propic']
        idtype = request.POST['idtype']
        idnum = request.POST['idnum']
        idimg = request.POST['idimg']
        resname = request.POST['resname']
        resad = request.POST['resad']
        license = request.POST['license']
        photo = request.POST['photo']
        wapp = request.POST['wapp']
        time = request.POST['time']
        user = request.POST['user']
        pswd = request.POST['pswd']
        cpswd = request.POST['cpswd']
        restegform = Restaurentregistration(full_name=fullname,date_of_birth=dob,e_mail=email,mobile_number=mob,gender=gender,profile_photo=propic,id_type=idtype,id_number=idnum,image_of_id=idimg,wapp_number=wapp,photos=photo,rest_name=resname,rest_address=resad,license_number=license,working_hours=time ,username=user,password=pswd,confirm_password=cpswd,status='waiting')
        restegform.save()
        return redirect('member:memlogin')
    return render (request, 'member/restaurentreg.html',)
def photographerreg (request):
    if request.method == 'POST':
        fullname = request.POST['fullname']
        dob = request.POST['dob']
        email = request.POST['email']
        mob = request.POST['mob']
        gender = request.POST['gender']
        propic = request.POST['propic']
        idtype = request.POST['idtype']
        idnum = request.POST['idnum']
        idimg = request.POST['idimg']
        sidtype = request.POST['sidtype']
        sidnum = request.POST['sidnum']
        sidimg = request.POST['sidimg']
        natn = request.POST['natn']
        state = request.POST['state']
        dist = request.POST['dist']
        street = request.POST['street']
        post = request.POST['post']
        pin = request.POST['pin']
        place = request.POST['place']
        time = request.POST['time']
        photo = request.POST['photo']
        wapp = request.POST['wapp']
        studio = request.POST['studio']
        amount = request.POST['amount']
        user = request.POST['user']
        cuser = request.POST['cuser']
        pswd = request.POST['pswd']
        cpswd = request.POST['cpswd']
        photoregform = Photographerregistration(full_name=fullname,date_of_birth=dob,e_mail=email,mobile_number=mob,gender=gender,profile_photo=propic,id_type=idtype,id_number=idnum,image_of_id=idimg,second_id_type=sidtype,second_id_number=sidnum,second_image_of_id=sidimg,nationality=natn,state=state,district=dist,street_name=street,post=post,pin_code=pin,wapp_number=wapp,photos=photo,available_place=place,available_time=time,studio_name=studio,amount_hours=amount,username=user,confirm_username=cuser,password=pswd,confirm_password=cpswd,status='waiting')
        photoregform.save()
        return redirect ('member:nphlogin')
    return render (request, 'member/photoreg.html')
def driverreg (request):
    if request.method == 'POST':
        fullname = request.POST['fullname']
        dob = request.POST['dob']
        email = request.POST['email']
        mob = request.POST['mob']
        gender = request.POST['gender']
        propic = request.POST['propic']
        idtype = request.POST['idtype']
        idnum = request.POST['idnum']
        idimg = request.POST['idimg']
        sidtype = request.POST['sidtype']
        sidnum = request.POST['sidnum']
        sidimg = request.POST['sidimg']
        natn = request.POST['natn']
        state = request.POST['state']
        dist = request.POST['dist']
        street = request.POST['street']
        post = request.POST['post']
        pin = request.POST['pin']
        place = request.POST['place']
        time = request.POST['time']
        license = request.POST['license']
        wapp = request.POST['wapp']
        model = request.POST['model']
        rc = request.POST['rc']
        user = request.POST['user']
        cuser = request.POST['cuser']
        pswd = request.POST['pswd']
        cpswd = request.POST['cpswd']
        driverregform = Driverregistration(full_name=fullname,date_of_birth=dob,e_mail=email,mobile_number=mob,gender=gender,profile_photo=propic,id_type=idtype,id_number=idnum,image_of_id=idimg,second_id_type=sidtype,second_id_number=sidnum,second_image_of_id=sidimg,nationality=natn,state=state,district=dist,street_name=street,post=post,pin_code=pin,wapp_number=wapp,license=license,available_place=place,available_time=time,rc=rc,vehicle_model=model,username=user,confirm_username=cuser,password=pswd,confirm_password=cpswd)
        driverregform.save()
    return render (request, 'member/driverreg.html')

def rest_mem_details(request):
    rest_members=Restaurentregistration.objects.filter(status='waiting')
    return render(request,'member/restmem.html' ,{'rest_mem':rest_members})
def ph_mem_details(request):
    ph_members=Photographerregistration.objects.filter(status='waiting')
    return render(request,'member/phmem.html' ,{'ph_mem':ph_members})
def ho_mem_details(request):
    ho_members=Hotelregistration.objects.filter(status='waiting')
    return render(request,'member/homem.html',{'ho_mem':ho_members})

def delete_rest_mem(request,restid):
    Restaurentregistration.objects.get(id=restid).delete()
    return redirect('member:nrestmem')
def delete_ph_mem(request,phid):
    Photographerregistration.objects.get(id=phid).delete()
def delete_ho_mem(request,hoid):
    Hotelregistration.objects.get(id=hoid).delete()    
    return redirect('member:nphmem')

def accept_rest_mem(request,restid):
    Restaurentregistration.objects.filter(id=restid).update(status='active')
    return redirect('member:waitinglist')
def ph_mem_accept(request,phid):
    Photographerregistration.objects.filter(id=phid).update(status='active')
    return redirect('member:waitinglist')
def ho_mem_accept(request,hoid):
    Hotelregistration.objects.filter(id=hoid).update(status='active')
    return redirect('member:waitinglist')
def dr_mem_accept(request,drid):
    Driverregistration.objects.filter(id=drid).update(status='active')

member/templates/member/phdashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>guideME</title>

    <link  rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">    
<style>
  
  .homebutn{
    border: none;
    width: 150px;
    font-size: 25px;
    padding: 1px;
    color: rgb(13, 56, 56);
    background-color: transparent;
    cursor: pointer;
    transition: 0.5s;
    border-radius: 100px;
    
        

    }
    .homebutn:hover {
        border:1px solid rgb(21, 94, 46);
        
    }
    
    
</style> 
 
</head>
<body>
  <div class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-light bg-light py-3 py-lg-5">
      <a class="navbar-brand" href="#">
        <img src="{% static 'images/logo.png' %}" width="50" height="50" class="d-inline-block align-top" alt="">
        
      </a>
      <a class="navbar-brand headding" href="#">
        <b style="font-size: 50px;">guideME</b>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
          

            <li><a class="nav-link active" href="{% url 'member:nmehome' %}"><button class="homebutn">home</button></a></li>
          </div>
      </div>
    </nav>
    phdashboard
      
      
    
  </div>

</body>
</html>    

member/templates/member/rejected.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>guideME</title>

    <link  rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">    
 <style>
    .loginbutn{
        width: 100px;
        border: 0px solid;
        position: relative;
        padding: 15px 0;
        text-align: center;
        margin: 20px 10px;
        font-weight: 50px;
        font-size: 20px;
        background:transparent;
        color: #138d89;
        cursor: pointer;
        transition: all 0.2s ease;
        border-radius: 100px;
        transition: 1.5s;
        

    }
    .loginbutn:hover {
        box-shadow: 0 5px 8px 0 #138d89 inset,0 5px 8px 0 #138d89,
                    0 5px 8px 0 #138d89 inset,0 5px 8px 0 #138d89;
        
    }
    .styled-table {
    border-collapse: collapse;
    margin: 25px 0;
    font-size: 0.9em;
    font-family: sans-serif;
    min-width: 400px;
    box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
}
.styled-table thead tr {
    background-color: #009879;
    color: #ffffff;
    text-align: left;
}
.styled-table th,
.styled-table td {
    padding: 12px 15px;
}
.styled-table tbody tr {
    border-bottom: 1px solid #dddddd;
}

.styled-table tbody tr:nth-of-type(even) {
    background-color: #f3f3f3;
}

.styled-table tbody tr:last-of-type {
    border-bottom: 2px solid #009879;
}
.styled-table tbody tr.active-row {
    font-weight: bold;
    color: #009879;
}
button {
    border: 1px solid green;
    background-color: #009879;
    color: rgb(243, 240, 240);
    border-radius: 6px;
}

    
 </style>
</head>
<body>
  <div class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-light bg-light py-3 py-lg-5">
      <a class="navbar-brand" href="#">
        <img src="{% static 'images/logo.png' %}" width="50" height="50" class="d-inline-block align-top" alt="">
        
      </a>
      <a class="navbar-brand headding" href="#">
        <b style="font-size: 50px;">guideME</b>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
          

            <li><a class="nav-link active" href="{% url 'member:accepted' %}"><button class="loginbutn">Accepted</button></a></li>
            <li><a class="nav-link active" href="{% url 'member:rejected' %}"><button class="loginbutn">Rejected</button></a></li>
            <li><a class="nav-link active" href="{% url 'gmadmin:application' %}"><button class="loginbutn">Back</button></a></li>

            
            
            
              
        </div>
      </div>
    </nav>
    <div class="restaurent">
        <table class="styled-table">
            <thead>
                <tr>
                    <th>Member name</th>
                    <th>email</th>
                    <th>mobile</th>
                    <th>gender</th>
                    <th>ID-type</th>
                    <th>ID-number</th>
                    <th>id-img</th>
                    <th>restaurent</th>
                    <th>restAddress</th>
                    <th>License</th>
                    <th>Wapp-num</th>
                    <th>Username</th>
                    <th>Password</th>
                    <th>accept/reject</th>
                    <th>delete</th>
                
                </tr>
            </thead>
            <tbody>
                <tr>
                    {% for r in reject %}
                    <tr>
                        <td>{{r.full_name}}</td>
                        <td>{{r.e_mail}}</td>
                        <td>{{r.mobile_number}}</td>
                        <td>{{r.gender}}</td>
                        <td>{{r.id_type}}</td>
                        <td>{{r.id_number}}</td>
                        <td>{{r.image_of_id}}</td>
                        <td>{{r.rest_name}}</td>
                        <td>{{r.rest_address}}</td>
                        <td>{{r.license_number}}</td>
                        <td>{{r.wapp_number}}</td>
                        <td>{{r.username}}</td>
                        <td>{{r.password}}</td>
                        <td><a href="{% url 'member:rest_mem_accept' r.id %}">Accept</a></td>
                        <td><a href="{% url 'member:rest_mem_delete' r.id %}">Delete</a></td>

                  
                    </tr>
                {% endfor %}
                </tr>
            
            </tbody>
        </table>
    </div>
    <div class="photographer">
        <table class="styled-table">
            <thead>
                <tr>
                    <th>Member name</th>
                    <th>dob</th>
                    <th>email</th>
                    <th>mobile</th>
                    <th>gender</th>
                    <th>ID-type</th>
                    <th>ID-number</th>
                    <th>id-img</th>
                    <th>av_place</th>
                    <th>av_time</th>
                    <th>studio</th>
                    <th>Username</th>
                    <th>Password</th>
                    <th>accept</th>
                    <th>delete</th>
                    
                </tr>
            </thead>
            <tbody>
                <tr>
                    {% for mem in ph_mem %}
                    <tr>
                        <td>{{mem.full_name}}</td>
                        <td>{{mem.date_of_birth}}</td>
                        <td>{{mem.e_mail}}</td>
                        <td>{{mem.mobile_number}}</td>
                        <td>{{mem.gender}}</td>
                        <td>{{mem.id_type}}</td>
                        <td>{{mem.id_number}}</td>
                        <td>{{mem.image_of_id}}</td>
                        <td>{{mem.available_place}}</td>
                        <td>{{mem.available_time}}</td>
                        <td>{{mem.studio}}</td>
                        <td>{{mem.Username}}</td>
                        <td>{{mem.password}}</td>
                        <td><a href="{% url 'member:ph_mem_accept' mem.id %}">Accept</a></td>
                        <td><a href="{% url 'member:ph_mem_delete' mem.id %}">Delete</a></td>
    
                      
                    </tr>
                {% endfor %}
                </tr>
                
            </tbody>
        </table>
    </div> 
    <div class="hotel">
        <table class="styled-table">
            <thead>
                <tr>
                    <th>Member name</th>
                    <th>email</th>
                    <th>mobile</th>
                    <th>gender</th>
                    <th>ID-type</th>
                    <th>ID-number</th>
                    <th>id-img</th>
                    <th>hotel</th>
                    <th>hotelAddress</th>
                    <th>License</th>
                    <th>Wapp-num</th>
                    <th>Username</th>
                    <th>Password</th>
                    <th>accept</th>
                    <th>reject</th>
                    
                </tr>
            </thead>
            <tbody>
                <tr>
                    {% for mem in ho_mem %}
                    <tr>
                        <td>{{mem.full_name}}</td>
                        <td>{{mem.e_mail}}</td>
                        <td>{{mem.mobile_number}}</td>
                        <td>{{mem.gender}}</td>
                        <td>{{mem.id_type}}</td>
                        <td>{{mem.id_number}}</td>
                        <td>{{mem.image_of_id}}</td>
                        <td>{{mem.hotel_name}}</td>
                        <td>{{mem.hotel_address}}</td>
                        <td>{{mem.license_photo}}</td>
                        <td>{{mem.wapp_number}}</td>
                        <td>{{mem.username}}</td>
                        <td>{{mem.password}}</td>
                        <td><a href="{% url 'member:ho_mem_accept' mem.id %}">Accept</a></td>
                        <td><a href="{% url 'member:ho_mem_delete' mem.id %}">Delete</a></td>
    
                      
                    </tr>
                {% endfor %}
                </tr>
                
            </tbody>
        </table>
    </div> 
    <div class="driver">
        <table class="styled-table photographer">
            <thead>
                <tr>
                    <tr>
                        <th>Member name</th>
                        <th>dob</th>
                        <th>email</th>
                        <th>mobile</th>
                        <th>gender</th>
                        <th>ID-type</th>
                        <th>ID-number</th>
                        <th>id-img</th>
                        <th>av_place</th>
                        <th>av_time</th>
                        <th>Vehicle</th>
                        <th>license</th>
                        <th>rc</th>
                        <th>Username</th>
                        <th>Password</th>
                        <th>accept</th>
                        <th>reject</th>
                        
                    </tr>
                
                </tr>
            </thead>
            <tbody>
                <tr>
                    {% for mem in dr_mem %}
                    <tr>
                        <td>{{mem.full_name}}</td>
                        <td>{{mem.date_of_birth}}</td>
                        <td>{{mem.e_mail}}</td>
                        <td>{{mem.mobile_number}}</td>
                        <td>{{mem.gender}}</td>
                        <td>{{mem.id_type}}</td>
                        <td>{{mem.id_number}}</td>
                        <td>{{mem.image_of_id}}</td>
                        <td>{{mem.available_place}}</td>
                        <td>{{mem.available_time}}</td>
                        <td>{{mem.vehicle_model}}</td>
                        <td>{{mem.license}}</td>
                        <td>{{mem.rc}}</td>
                        <td>{{mem.username}}</td>
                        <td>{{mem.password}}</td>
                        <td><a href="{% url 'member:dr_mem_reject' mem.id %}">Reject</a></td>
    
                      
                    </tr>
                {% endfor %}
                </tr>
            
            </tbody>
        </table>
    </div>  
  </div>

    
</body> 
</html>   

member/templates/member/waiting.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>guideME</title>

    <link  rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">    
<style>
  
  .homebutn{
    border: none;
    width: 150px;
    font-size: 25px;
    padding: 1px;
    color: rgb(13, 56, 56);
    background-color: transparent;
    cursor: pointer;
    transition: 0.5s;
    border-radius: 100px;
    
        

    }
    .homebutn:hover {
        border:1px solid rgb(21, 94, 46);
        
    }
    
 
    
</style> 
 
</head>
<body>
  <div class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-light bg-light py-3 py-lg-5">
      <a class="navbar-brand" href="#">
        <img src="{% static 'images/logo.png' %}" width="50" height="50" class="d-inline-block align-top" alt="">
        
      </a>
      <a class="navbar-brand headding" href="#">
        <b style="font-size: 50px;">guideME</b>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
          

            <li><a class="nav-link active" href="{% url 'member:nmehome' %}"><button class="homebutn">home</button></a></li>
          </div>
      </div>
    </nav>
     
      <div class="waiting">
        <h1>please wait , you can login within minutes</h1>
      </div>
      
    
  </div>

</body>
</html>    


  
   